### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sherifomran** [ARMmbed/mbed-os-experimental-ble-services#20]
**Describe the bug**

the bluetooth driver has a bug exactly when a device (ios) connects to the peripheral (nordic chip) and the device sleeps and causing the connection to disconnect from one side only, the peripheral can not detect this disconnection and must get a hardware reset in order to be able to connect to it again.
It should detect the disconnection using a time or indication or something else.

**To Reproduce**
connect ios to peripheral and let it sleep. After some minuites it is disconnected from one side, try reconnection, it will fail.

**Expected behavior**
Reconnection sucessful

**Screenshots**

**Context (please complete the following information):**
 - Mbed OS version: [e.g. 6.4]
 - Compiler:  [e.g. GCC, ARM, ..]
 - Target [e.g. NRF52840_DK]

**Additional context**

**Comment by paul-szczepanek-arm** [comment]
if you're connected BLE should stop you from sleeping and wake you up to maintain the connection. How are you sleeping? Please provide repro steps.

But more importantly, this is not the right repo to submit mbed-os issues, please open your issues in:
https://github.com/ARMmbed/mbed-os
This repo is for community supplied services.

**Comment by sherifomran** [comment]
sleep on the mobile is independent of the bluetooth. The mobile can sleep and then disconnects from one side, the gadget is still seeing a slave being connected but he is idle since some seconds but it does not reset the connection.

**Comment by paul-szczepanek-arm** [comment]
So you're saying that the mobile (what client? nrf tools?) connects to a gatt server on an mbedos board. It goes out of range/asleep and times out the connection but mbed-os doesn't give you the onDisconnection event and thinks the connection is still present?

**Comment by sherifomran** [comment]
yes this is what i say!

**Comment by paul-szczepanek-arm** [comment]
Without code it's impossible to say what is wrong, the onDisconnection works fine as far as I can tell, please open an issue at:
https://github.com/ARMmbed/mbed-os/issues
and attach the code you're running and the repro steps.

**Comment by paul-szczepanek-arm** [comment]
This is repo is for new ble services, please use mbed-os to report problems with ble in general

**Comment by paul-szczepanek-arm** [comment]
I read the thread you made on the arduino forum. This is unlikely to even be an mbed-os bug. Try using an up to date example and if you're still having issues post the code, otherwise it's impossible to say what the problem is. For general support please try: https://forums.mbed.com/
