### ISSUE TITLE
Link Loss Service

### ISSUE THREAD

**Issue by AGlass0fMilk** [ARMmbed/mbed-os-experimental-ble-services#3]
### Proposed UUID(s) or link to specification document:

https://www.bluetooth.org/DocMan/handlers/DownloadDoc.ashx?doc_id=303198

## Overview:

The Link Loss Service uses the Alert Level characteristic to cause an alert in the device when the link is lost.

## Detailed Description
The API should include a way to register an application callback to be executed upon an unexpected disconnection. The service can register a handler for `GapEventHandler::onDisconnectionComplete` and check the given cause of the disconnection, executing the application callback as appropriate.

The Alert Level Characteristic used in this service should be declared separately for reuse in other services.

**Comment by pan-** [comment]
@AGlass0fMilk Do you think https://github.com/ARMmbed/mbed-os-experimental-ble-services/pull/14 fulfill this request ?

**Comment by AGlass0fMilk** [comment]
> @AGlass0fMilk Do you think #14 fulfill this request ?

@pan- 

I think that PR is sufficient. I will close this issue.
