### ISSUE TITLE
[BUG] Integration tests for DeviceInformation fail to build

### ISSUE THREAD

**Issue by noonfom** [ARMmbed/mbed-os-experimental-ble-services#54]
**Describe the bug**
The integration tests for [DeviceInformation](https://github.com/ARMmbed/mbed-os-experimental-ble-services/tree/github-ci/tests/TESTS/DeviceInformation) fail to build as the dependencies are not symlinked in `boostrap.sh`. 

**To Reproduce**
Try to build the BLE app using the steps in the [integration testing guide](https://github.com/ARMmbed/mbed-os-experimental-ble-services/blob/github-ci/tests/TESTS/README.md#building-and-running-integration-tests).  

**Expected behavior**
The BLE app should build. Please symlink the dependencies in `boostrap.sh`.

**Comment by paul-szczepanek-arm** [comment]
Thanks. The service was written before your reorg. I added the symlinks.
